// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the TaskReportV1Step type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskReportV1Step{}

// TaskReportV1Step Execution state of one rule sequence step. Pairs 1:1 with the rule's ordered steps within the containing stage and shares its index. Unresolved components (`totalComponents - succeededComponents - failedComponents`) have no reported terminal outcome, even if the step has failed or timed out.
type TaskReportV1Step struct {
	// Component class this step targets, e.g. `Compute`, `NVLSwitch`, `PowerShelf`.
	ComponentType string             `json:"componentType"`
	Status        TaskReportV1Status `json:"status"`
	// Count of components of `componentType` this step targets, including zero for skipped steps.
	TotalComponents int32 `json:"totalComponents"`
	// Number of requested components reported as successfully completed, combining the latest successful poll of the current batch with outcomes from completed batches. May decrease if a component is absent from a later poll. Zero when no successful outcomes have been reported.
	SucceededComponents int32 `json:"succeededComponents"`
	// Number of requested components reported as `Failed`, using the same counting rules as `succeededComponents`. Zero when no failed outcomes have been reported.
	FailedComponents int32 `json:"failedComponents"`
	// Set when the step leaves `pending`. `skipped` steps carry no timestamp.
	StartedAt *time.Time `json:"startedAt,omitempty"`
	// Set when the step reaches a terminal state.
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	// Failure summary when `status == failed`. Truncated to 512 bytes.
	Error *string `json:"error,omitempty"`
}

type _TaskReportV1Step TaskReportV1Step

// NewTaskReportV1Step instantiates a new TaskReportV1Step object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskReportV1Step(componentType string, status TaskReportV1Status, totalComponents int32, succeededComponents int32, failedComponents int32) *TaskReportV1Step {
	this := TaskReportV1Step{}
	this.ComponentType = componentType
	this.Status = status
	this.TotalComponents = totalComponents
	this.SucceededComponents = succeededComponents
	this.FailedComponents = failedComponents
	return &this
}

// NewTaskReportV1StepWithDefaults instantiates a new TaskReportV1Step object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskReportV1StepWithDefaults() *TaskReportV1Step {
	this := TaskReportV1Step{}
	return &this
}

// GetComponentType returns the ComponentType field value
func (o *TaskReportV1Step) GetComponentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentType
}

// GetComponentTypeOk returns a tuple with the ComponentType field value
// and a boolean to check if the value has been set.
func (o *TaskReportV1Step) GetComponentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentType, true
}

// SetComponentType sets field value
func (o *TaskReportV1Step) SetComponentType(v string) {
	o.ComponentType = v
}

// GetStatus returns the Status field value
func (o *TaskReportV1Step) GetStatus() TaskReportV1Status {
	if o == nil {
		var ret TaskReportV1Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TaskReportV1Step) GetStatusOk() (*TaskReportV1Status, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TaskReportV1Step) SetStatus(v TaskReportV1Status) {
	o.Status = v
}

// GetTotalComponents returns the TotalComponents field value
func (o *TaskReportV1Step) GetTotalComponents() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalComponents
}

// GetTotalComponentsOk returns a tuple with the TotalComponents field value
// and a boolean to check if the value has been set.
func (o *TaskReportV1Step) GetTotalComponentsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalComponents, true
}

// SetTotalComponents sets field value
func (o *TaskReportV1Step) SetTotalComponents(v int32) {
	o.TotalComponents = v
}

// GetSucceededComponents returns the SucceededComponents field value
func (o *TaskReportV1Step) GetSucceededComponents() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SucceededComponents
}

// GetSucceededComponentsOk returns a tuple with the SucceededComponents field value
// and a boolean to check if the value has been set.
func (o *TaskReportV1Step) GetSucceededComponentsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SucceededComponents, true
}

// SetSucceededComponents sets field value
func (o *TaskReportV1Step) SetSucceededComponents(v int32) {
	o.SucceededComponents = v
}

// GetFailedComponents returns the FailedComponents field value
func (o *TaskReportV1Step) GetFailedComponents() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FailedComponents
}

// GetFailedComponentsOk returns a tuple with the FailedComponents field value
// and a boolean to check if the value has been set.
func (o *TaskReportV1Step) GetFailedComponentsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedComponents, true
}

// SetFailedComponents sets field value
func (o *TaskReportV1Step) SetFailedComponents(v int32) {
	o.FailedComponents = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *TaskReportV1Step) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskReportV1Step) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *TaskReportV1Step) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *TaskReportV1Step) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise.
func (o *TaskReportV1Step) GetFinishedAt() time.Time {
	if o == nil || IsNil(o.FinishedAt) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskReportV1Step) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FinishedAt) {
		return nil, false
	}
	return o.FinishedAt, true
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *TaskReportV1Step) HasFinishedAt() bool {
	if o != nil && !IsNil(o.FinishedAt) {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given time.Time and assigns it to the FinishedAt field.
func (o *TaskReportV1Step) SetFinishedAt(v time.Time) {
	o.FinishedAt = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *TaskReportV1Step) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskReportV1Step) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *TaskReportV1Step) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *TaskReportV1Step) SetError(v string) {
	o.Error = &v
}

func (o TaskReportV1Step) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskReportV1Step) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["componentType"] = o.ComponentType
	toSerialize["status"] = o.Status
	toSerialize["totalComponents"] = o.TotalComponents
	toSerialize["succeededComponents"] = o.SucceededComponents
	toSerialize["failedComponents"] = o.FailedComponents
	if !IsNil(o.StartedAt) {
		toSerialize["startedAt"] = o.StartedAt
	}
	if !IsNil(o.FinishedAt) {
		toSerialize["finishedAt"] = o.FinishedAt
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *TaskReportV1Step) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"componentType",
		"status",
		"totalComponents",
		"succeededComponents",
		"failedComponents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskReportV1Step := _TaskReportV1Step{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTaskReportV1Step)

	if err != nil {
		return err
	}

	*o = TaskReportV1Step(varTaskReportV1Step)

	return err
}

type NullableTaskReportV1Step struct {
	value *TaskReportV1Step
	isSet bool
}

func (v NullableTaskReportV1Step) Get() *TaskReportV1Step {
	return v.value
}

func (v *NullableTaskReportV1Step) Set(val *TaskReportV1Step) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskReportV1Step) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskReportV1Step) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskReportV1Step(val *TaskReportV1Step) *NullableTaskReportV1Step {
	return &NullableTaskReportV1Step{value: val, isSet: true}
}

func (v NullableTaskReportV1Step) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskReportV1Step) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
