// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineInstanceTypeTenantStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineInstanceTypeTenantStats{}

// MachineInstanceTypeTenantStats Per-tenant allocation stats for one Instance Type
type MachineInstanceTypeTenantStats struct {
	// Unique UUID v4 identifier for the Tenant
	Id *string `json:"id,omitempty"`
	// Name of the Tenant
	Name *string `json:"name,omitempty"`
	// Number of Machines allocated to this Tenant for this Instance Type
	Allocated *int32 `json:"allocated,omitempty"`
	// Usage status of Machines for this Tenant and Instance Type
	UsedMachineStats *MachineStatusBreakdown `json:"usedMachineStats,omitempty"`
	// Individual Allocations for this Tenant and Instance Type
	Allocations []MachineInstanceTypeTenantAllocationStats `json:"allocations,omitempty"`
}

// NewMachineInstanceTypeTenantStats instantiates a new MachineInstanceTypeTenantStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineInstanceTypeTenantStats() *MachineInstanceTypeTenantStats {
	this := MachineInstanceTypeTenantStats{}
	return &this
}

// NewMachineInstanceTypeTenantStatsWithDefaults instantiates a new MachineInstanceTypeTenantStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineInstanceTypeTenantStatsWithDefaults() *MachineInstanceTypeTenantStats {
	this := MachineInstanceTypeTenantStats{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MachineInstanceTypeTenantStats) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInstanceTypeTenantStats) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MachineInstanceTypeTenantStats) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MachineInstanceTypeTenantStats) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MachineInstanceTypeTenantStats) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInstanceTypeTenantStats) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MachineInstanceTypeTenantStats) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MachineInstanceTypeTenantStats) SetName(v string) {
	o.Name = &v
}

// GetAllocated returns the Allocated field value if set, zero value otherwise.
func (o *MachineInstanceTypeTenantStats) GetAllocated() int32 {
	if o == nil || IsNil(o.Allocated) {
		var ret int32
		return ret
	}
	return *o.Allocated
}

// GetAllocatedOk returns a tuple with the Allocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInstanceTypeTenantStats) GetAllocatedOk() (*int32, bool) {
	if o == nil || IsNil(o.Allocated) {
		return nil, false
	}
	return o.Allocated, true
}

// HasAllocated returns a boolean if a field has been set.
func (o *MachineInstanceTypeTenantStats) HasAllocated() bool {
	if o != nil && !IsNil(o.Allocated) {
		return true
	}

	return false
}

// SetAllocated gets a reference to the given int32 and assigns it to the Allocated field.
func (o *MachineInstanceTypeTenantStats) SetAllocated(v int32) {
	o.Allocated = &v
}

// GetUsedMachineStats returns the UsedMachineStats field value if set, zero value otherwise.
func (o *MachineInstanceTypeTenantStats) GetUsedMachineStats() MachineStatusBreakdown {
	if o == nil || IsNil(o.UsedMachineStats) {
		var ret MachineStatusBreakdown
		return ret
	}
	return *o.UsedMachineStats
}

// GetUsedMachineStatsOk returns a tuple with the UsedMachineStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInstanceTypeTenantStats) GetUsedMachineStatsOk() (*MachineStatusBreakdown, bool) {
	if o == nil || IsNil(o.UsedMachineStats) {
		return nil, false
	}
	return o.UsedMachineStats, true
}

// HasUsedMachineStats returns a boolean if a field has been set.
func (o *MachineInstanceTypeTenantStats) HasUsedMachineStats() bool {
	if o != nil && !IsNil(o.UsedMachineStats) {
		return true
	}

	return false
}

// SetUsedMachineStats gets a reference to the given MachineStatusBreakdown and assigns it to the UsedMachineStats field.
func (o *MachineInstanceTypeTenantStats) SetUsedMachineStats(v MachineStatusBreakdown) {
	o.UsedMachineStats = &v
}

// GetAllocations returns the Allocations field value if set, zero value otherwise.
func (o *MachineInstanceTypeTenantStats) GetAllocations() []MachineInstanceTypeTenantAllocationStats {
	if o == nil || IsNil(o.Allocations) {
		var ret []MachineInstanceTypeTenantAllocationStats
		return ret
	}
	return o.Allocations
}

// GetAllocationsOk returns a tuple with the Allocations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInstanceTypeTenantStats) GetAllocationsOk() ([]MachineInstanceTypeTenantAllocationStats, bool) {
	if o == nil || IsNil(o.Allocations) {
		return nil, false
	}
	return o.Allocations, true
}

// HasAllocations returns a boolean if a field has been set.
func (o *MachineInstanceTypeTenantStats) HasAllocations() bool {
	if o != nil && !IsNil(o.Allocations) {
		return true
	}

	return false
}

// SetAllocations gets a reference to the given []MachineInstanceTypeTenantAllocationStats and assigns it to the Allocations field.
func (o *MachineInstanceTypeTenantStats) SetAllocations(v []MachineInstanceTypeTenantAllocationStats) {
	o.Allocations = v
}

func (o MachineInstanceTypeTenantStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineInstanceTypeTenantStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Allocated) {
		toSerialize["allocated"] = o.Allocated
	}
	if !IsNil(o.UsedMachineStats) {
		toSerialize["usedMachineStats"] = o.UsedMachineStats
	}
	if !IsNil(o.Allocations) {
		toSerialize["allocations"] = o.Allocations
	}
	return toSerialize, nil
}

type NullableMachineInstanceTypeTenantStats struct {
	value *MachineInstanceTypeTenantStats
	isSet bool
}

func (v NullableMachineInstanceTypeTenantStats) Get() *MachineInstanceTypeTenantStats {
	return v.value
}

func (v *NullableMachineInstanceTypeTenantStats) Set(val *MachineInstanceTypeTenantStats) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineInstanceTypeTenantStats) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineInstanceTypeTenantStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineInstanceTypeTenantStats(val *MachineInstanceTypeTenantStats) *NullableMachineInstanceTypeTenantStats {
	return &NullableMachineInstanceTypeTenantStats{value: val, isSet: true}
}

func (v NullableMachineInstanceTypeTenantStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineInstanceTypeTenantStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
