// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineInstanceTypeTenantAllocationStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineInstanceTypeTenantAllocationStats{}

// MachineInstanceTypeTenantAllocationStats Stats for a single Allocation within a Tenant's Instance Type stats
type MachineInstanceTypeTenantAllocationStats struct {
	// Unique UUID v4 identifier for the Allocation
	Id *string `json:"id,omitempty"`
	// Name of the Allocation
	Name *string `json:"name,omitempty"`
	// Number of Machines in this Allocation for the Instance Type
	Allocated *int32 `json:"allocated,omitempty"`
}

// NewMachineInstanceTypeTenantAllocationStats instantiates a new MachineInstanceTypeTenantAllocationStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineInstanceTypeTenantAllocationStats() *MachineInstanceTypeTenantAllocationStats {
	this := MachineInstanceTypeTenantAllocationStats{}
	return &this
}

// NewMachineInstanceTypeTenantAllocationStatsWithDefaults instantiates a new MachineInstanceTypeTenantAllocationStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineInstanceTypeTenantAllocationStatsWithDefaults() *MachineInstanceTypeTenantAllocationStats {
	this := MachineInstanceTypeTenantAllocationStats{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MachineInstanceTypeTenantAllocationStats) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInstanceTypeTenantAllocationStats) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MachineInstanceTypeTenantAllocationStats) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MachineInstanceTypeTenantAllocationStats) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MachineInstanceTypeTenantAllocationStats) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInstanceTypeTenantAllocationStats) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MachineInstanceTypeTenantAllocationStats) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MachineInstanceTypeTenantAllocationStats) SetName(v string) {
	o.Name = &v
}

// GetAllocated returns the Allocated field value if set, zero value otherwise.
func (o *MachineInstanceTypeTenantAllocationStats) GetAllocated() int32 {
	if o == nil || IsNil(o.Allocated) {
		var ret int32
		return ret
	}
	return *o.Allocated
}

// GetAllocatedOk returns a tuple with the Allocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInstanceTypeTenantAllocationStats) GetAllocatedOk() (*int32, bool) {
	if o == nil || IsNil(o.Allocated) {
		return nil, false
	}
	return o.Allocated, true
}

// HasAllocated returns a boolean if a field has been set.
func (o *MachineInstanceTypeTenantAllocationStats) HasAllocated() bool {
	if o != nil && !IsNil(o.Allocated) {
		return true
	}

	return false
}

// SetAllocated gets a reference to the given int32 and assigns it to the Allocated field.
func (o *MachineInstanceTypeTenantAllocationStats) SetAllocated(v int32) {
	o.Allocated = &v
}

func (o MachineInstanceTypeTenantAllocationStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineInstanceTypeTenantAllocationStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Allocated) {
		toSerialize["allocated"] = o.Allocated
	}
	return toSerialize, nil
}

type NullableMachineInstanceTypeTenantAllocationStats struct {
	value *MachineInstanceTypeTenantAllocationStats
	isSet bool
}

func (v NullableMachineInstanceTypeTenantAllocationStats) Get() *MachineInstanceTypeTenantAllocationStats {
	return v.value
}

func (v *NullableMachineInstanceTypeTenantAllocationStats) Set(val *MachineInstanceTypeTenantAllocationStats) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineInstanceTypeTenantAllocationStats) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineInstanceTypeTenantAllocationStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineInstanceTypeTenantAllocationStats(val *MachineInstanceTypeTenantAllocationStats) *NullableMachineInstanceTypeTenantAllocationStats {
	return &NullableMachineInstanceTypeTenantAllocationStats{value: val, isSet: true}
}

func (v NullableMachineInstanceTypeTenantAllocationStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineInstanceTypeTenantAllocationStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
