// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the NICoAPIError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NICoAPIError{}

// NICoAPIError Describes the error response from NVIDIA Infra Controller REST API
type NICoAPIError struct {
	// Source of the error.
	Source *string `json:"source,omitempty"`
	// Message describing the error
	Message *string `json:"message,omitempty"`
	// Additional data about the error
	Data map[string]interface{} `json:"data,omitempty"`
	// Optional classification of a rejected request. True permits a bounded, delayed retry; it does not guarantee availability or eventual success. False means do not automatically repeat the request. Omission means unclassified, not false. Instance create reports true only for a unique current instance owned by the requesting tenant with status Terminating; conflicting live operations report false. Missing or ambiguous machine associations remain unclassified.
	Retryable *bool `json:"retryable,omitempty"`
	// Optional minimum delay in seconds before a permitted retry, present only with retryable true. Omission means no server delay estimate is available; use bounded client backoff. Instance release-pending errors omit this field.
	RetryAfterSeconds *int32 `json:"retryAfterSeconds,omitempty"`
	// Reconcile means an instance create outcome is uncertain, including a workflow start acknowledgement failure, timeout, lost workflow-result read, site transport/server failure, or REST commit failure after allocation. retryable is false. Check the original operation and ownership before another create; an empty REST result alone does not rule out allocation on the site. Omitted on errors without a recovery action. A lost HTTP response has no metadata: reconcile that outcome rather than blindly retrying.
	RecoveryAction *string `json:"recoveryAction,omitempty"`
}

// NewNICoAPIError instantiates a new NICoAPIError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNICoAPIError() *NICoAPIError {
	this := NICoAPIError{}
	return &this
}

// NewNICoAPIErrorWithDefaults instantiates a new NICoAPIError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNICoAPIErrorWithDefaults() *NICoAPIError {
	this := NICoAPIError{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *NICoAPIError) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NICoAPIError) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *NICoAPIError) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *NICoAPIError) SetSource(v string) {
	o.Source = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *NICoAPIError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NICoAPIError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *NICoAPIError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *NICoAPIError) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NICoAPIError) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NICoAPIError) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NICoAPIError) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *NICoAPIError) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetRetryable returns the Retryable field value if set, zero value otherwise.
func (o *NICoAPIError) GetRetryable() bool {
	if o == nil || IsNil(o.Retryable) {
		var ret bool
		return ret
	}
	return *o.Retryable
}

// GetRetryableOk returns a tuple with the Retryable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NICoAPIError) GetRetryableOk() (*bool, bool) {
	if o == nil || IsNil(o.Retryable) {
		return nil, false
	}
	return o.Retryable, true
}

// HasRetryable returns a boolean if a field has been set.
func (o *NICoAPIError) HasRetryable() bool {
	if o != nil && !IsNil(o.Retryable) {
		return true
	}

	return false
}

// SetRetryable gets a reference to the given bool and assigns it to the Retryable field.
func (o *NICoAPIError) SetRetryable(v bool) {
	o.Retryable = &v
}

// GetRetryAfterSeconds returns the RetryAfterSeconds field value if set, zero value otherwise.
func (o *NICoAPIError) GetRetryAfterSeconds() int32 {
	if o == nil || IsNil(o.RetryAfterSeconds) {
		var ret int32
		return ret
	}
	return *o.RetryAfterSeconds
}

// GetRetryAfterSecondsOk returns a tuple with the RetryAfterSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NICoAPIError) GetRetryAfterSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryAfterSeconds) {
		return nil, false
	}
	return o.RetryAfterSeconds, true
}

// HasRetryAfterSeconds returns a boolean if a field has been set.
func (o *NICoAPIError) HasRetryAfterSeconds() bool {
	if o != nil && !IsNil(o.RetryAfterSeconds) {
		return true
	}

	return false
}

// SetRetryAfterSeconds gets a reference to the given int32 and assigns it to the RetryAfterSeconds field.
func (o *NICoAPIError) SetRetryAfterSeconds(v int32) {
	o.RetryAfterSeconds = &v
}

// GetRecoveryAction returns the RecoveryAction field value if set, zero value otherwise.
func (o *NICoAPIError) GetRecoveryAction() string {
	if o == nil || IsNil(o.RecoveryAction) {
		var ret string
		return ret
	}
	return *o.RecoveryAction
}

// GetRecoveryActionOk returns a tuple with the RecoveryAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NICoAPIError) GetRecoveryActionOk() (*string, bool) {
	if o == nil || IsNil(o.RecoveryAction) {
		return nil, false
	}
	return o.RecoveryAction, true
}

// HasRecoveryAction returns a boolean if a field has been set.
func (o *NICoAPIError) HasRecoveryAction() bool {
	if o != nil && !IsNil(o.RecoveryAction) {
		return true
	}

	return false
}

// SetRecoveryAction gets a reference to the given string and assigns it to the RecoveryAction field.
func (o *NICoAPIError) SetRecoveryAction(v string) {
	o.RecoveryAction = &v
}

func (o NICoAPIError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NICoAPIError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Retryable) {
		toSerialize["retryable"] = o.Retryable
	}
	if !IsNil(o.RetryAfterSeconds) {
		toSerialize["retryAfterSeconds"] = o.RetryAfterSeconds
	}
	if !IsNil(o.RecoveryAction) {
		toSerialize["recoveryAction"] = o.RecoveryAction
	}
	return toSerialize, nil
}

type NullableNICoAPIError struct {
	value *NICoAPIError
	isSet bool
}

func (v NullableNICoAPIError) Get() *NICoAPIError {
	return v.value
}

func (v *NullableNICoAPIError) Set(val *NICoAPIError) {
	v.value = val
	v.isSet = true
}

func (v NullableNICoAPIError) IsSet() bool {
	return v.isSet
}

func (v *NullableNICoAPIError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNICoAPIError(val *NICoAPIError) *NullableNICoAPIError {
	return &NullableNICoAPIError{value: val, isSet: true}
}

func (v NullableNICoAPIError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNICoAPIError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
