// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TrayHealthReportEntryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrayHealthReportEntryRequest{}

// TrayHealthReportEntryRequest Request to add or update a Tray health report override.
type TrayHealthReportEntryRequest struct {
	// ID of the Site that owns the Tray.
	SiteId string `json:"siteId"`
	// Tray type used to select the corresponding component health-report resource.
	Type string `json:"type"`
	// Health report source.
	Source string `json:"source"`
	// Results from successful health probes for the Tray.
	Successes []MachineHealthProbeSuccess `json:"successes,omitempty"`
	// Results from failed health probes for the Tray.
	Alerts []MachineHealthProbeAlert `json:"alerts,omitempty"`
	// How updates to this health report should be handled
	Mode string `json:"mode"`
}

type _TrayHealthReportEntryRequest TrayHealthReportEntryRequest

// NewTrayHealthReportEntryRequest instantiates a new TrayHealthReportEntryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrayHealthReportEntryRequest(siteId string, type_ string, source string, mode string) *TrayHealthReportEntryRequest {
	this := TrayHealthReportEntryRequest{}
	this.SiteId = siteId
	this.Type = type_
	this.Source = source
	this.Mode = mode
	return &this
}

// NewTrayHealthReportEntryRequestWithDefaults instantiates a new TrayHealthReportEntryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrayHealthReportEntryRequestWithDefaults() *TrayHealthReportEntryRequest {
	this := TrayHealthReportEntryRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *TrayHealthReportEntryRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *TrayHealthReportEntryRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *TrayHealthReportEntryRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetType returns the Type field value
func (o *TrayHealthReportEntryRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrayHealthReportEntryRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrayHealthReportEntryRequest) SetType(v string) {
	o.Type = v
}

// GetSource returns the Source field value
func (o *TrayHealthReportEntryRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *TrayHealthReportEntryRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *TrayHealthReportEntryRequest) SetSource(v string) {
	o.Source = v
}

// GetSuccesses returns the Successes field value if set, zero value otherwise.
func (o *TrayHealthReportEntryRequest) GetSuccesses() []MachineHealthProbeSuccess {
	if o == nil || IsNil(o.Successes) {
		var ret []MachineHealthProbeSuccess
		return ret
	}
	return o.Successes
}

// GetSuccessesOk returns a tuple with the Successes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrayHealthReportEntryRequest) GetSuccessesOk() ([]MachineHealthProbeSuccess, bool) {
	if o == nil || IsNil(o.Successes) {
		return nil, false
	}
	return o.Successes, true
}

// HasSuccesses returns a boolean if a field has been set.
func (o *TrayHealthReportEntryRequest) HasSuccesses() bool {
	if o != nil && !IsNil(o.Successes) {
		return true
	}

	return false
}

// SetSuccesses gets a reference to the given []MachineHealthProbeSuccess and assigns it to the Successes field.
func (o *TrayHealthReportEntryRequest) SetSuccesses(v []MachineHealthProbeSuccess) {
	o.Successes = v
}

// GetAlerts returns the Alerts field value if set, zero value otherwise.
func (o *TrayHealthReportEntryRequest) GetAlerts() []MachineHealthProbeAlert {
	if o == nil || IsNil(o.Alerts) {
		var ret []MachineHealthProbeAlert
		return ret
	}
	return o.Alerts
}

// GetAlertsOk returns a tuple with the Alerts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrayHealthReportEntryRequest) GetAlertsOk() ([]MachineHealthProbeAlert, bool) {
	if o == nil || IsNil(o.Alerts) {
		return nil, false
	}
	return o.Alerts, true
}

// HasAlerts returns a boolean if a field has been set.
func (o *TrayHealthReportEntryRequest) HasAlerts() bool {
	if o != nil && !IsNil(o.Alerts) {
		return true
	}

	return false
}

// SetAlerts gets a reference to the given []MachineHealthProbeAlert and assigns it to the Alerts field.
func (o *TrayHealthReportEntryRequest) SetAlerts(v []MachineHealthProbeAlert) {
	o.Alerts = v
}

// GetMode returns the Mode field value
func (o *TrayHealthReportEntryRequest) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *TrayHealthReportEntryRequest) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *TrayHealthReportEntryRequest) SetMode(v string) {
	o.Mode = v
}

func (o TrayHealthReportEntryRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrayHealthReportEntryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["type"] = o.Type
	toSerialize["source"] = o.Source
	if !IsNil(o.Successes) {
		toSerialize["successes"] = o.Successes
	}
	if !IsNil(o.Alerts) {
		toSerialize["alerts"] = o.Alerts
	}
	toSerialize["mode"] = o.Mode
	return toSerialize, nil
}

func (o *TrayHealthReportEntryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"type",
		"source",
		"mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrayHealthReportEntryRequest := _TrayHealthReportEntryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTrayHealthReportEntryRequest)

	if err != nil {
		return err
	}

	*o = TrayHealthReportEntryRequest(varTrayHealthReportEntryRequest)

	return err
}

type NullableTrayHealthReportEntryRequest struct {
	value *TrayHealthReportEntryRequest
	isSet bool
}

func (v NullableTrayHealthReportEntryRequest) Get() *TrayHealthReportEntryRequest {
	return v.value
}

func (v *NullableTrayHealthReportEntryRequest) Set(val *TrayHealthReportEntryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTrayHealthReportEntryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTrayHealthReportEntryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrayHealthReportEntryRequest(val *TrayHealthReportEntryRequest) *NullableTrayHealthReportEntryRequest {
	return &NullableTrayHealthReportEntryRequest{value: val, isSet: true}
}

func (v NullableTrayHealthReportEntryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrayHealthReportEntryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
