// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedPowerShelfList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedPowerShelfList{}

// ExpectedPowerShelfList Complete replacement set of Expected Power Shelves for one Site. Every entry must use the top-level `siteId`; the array may be empty to clear the set.
type ExpectedPowerShelfList struct {
	// ID of the Site whose Expected Power Shelves should be replaced
	SiteId string `json:"siteId"`
	// Full desired Expected Power Shelf set; BMC MAC addresses and shelf serial numbers must be unique
	ExpectedPowerShelves []ExpectedPowerShelfCreateRequest `json:"expectedPowerShelves"`
}

type _ExpectedPowerShelfList ExpectedPowerShelfList

// NewExpectedPowerShelfList instantiates a new ExpectedPowerShelfList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedPowerShelfList(siteId string, expectedPowerShelves []ExpectedPowerShelfCreateRequest) *ExpectedPowerShelfList {
	this := ExpectedPowerShelfList{}
	this.SiteId = siteId
	this.ExpectedPowerShelves = expectedPowerShelves
	return &this
}

// NewExpectedPowerShelfListWithDefaults instantiates a new ExpectedPowerShelfList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedPowerShelfListWithDefaults() *ExpectedPowerShelfList {
	this := ExpectedPowerShelfList{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedPowerShelfList) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfList) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedPowerShelfList) SetSiteId(v string) {
	o.SiteId = v
}

// GetExpectedPowerShelves returns the ExpectedPowerShelves field value
func (o *ExpectedPowerShelfList) GetExpectedPowerShelves() []ExpectedPowerShelfCreateRequest {
	if o == nil {
		var ret []ExpectedPowerShelfCreateRequest
		return ret
	}

	return o.ExpectedPowerShelves
}

// GetExpectedPowerShelvesOk returns a tuple with the ExpectedPowerShelves field value
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfList) GetExpectedPowerShelvesOk() ([]ExpectedPowerShelfCreateRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedPowerShelves, true
}

// SetExpectedPowerShelves sets field value
func (o *ExpectedPowerShelfList) SetExpectedPowerShelves(v []ExpectedPowerShelfCreateRequest) {
	o.ExpectedPowerShelves = v
}

func (o ExpectedPowerShelfList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedPowerShelfList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["expectedPowerShelves"] = o.ExpectedPowerShelves
	return toSerialize, nil
}

func (o *ExpectedPowerShelfList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"expectedPowerShelves",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedPowerShelfList := _ExpectedPowerShelfList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExpectedPowerShelfList)

	if err != nil {
		return err
	}

	*o = ExpectedPowerShelfList(varExpectedPowerShelfList)

	return err
}

type NullableExpectedPowerShelfList struct {
	value *ExpectedPowerShelfList
	isSet bool
}

func (v NullableExpectedPowerShelfList) Get() *ExpectedPowerShelfList {
	return v.value
}

func (v *NullableExpectedPowerShelfList) Set(val *ExpectedPowerShelfList) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedPowerShelfList) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedPowerShelfList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedPowerShelfList(val *ExpectedPowerShelfList) *NullableExpectedPowerShelfList {
	return &NullableExpectedPowerShelfList{value: val, isSet: true}
}

func (v NullableExpectedPowerShelfList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedPowerShelfList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
