// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AggregateHealth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregateHealth{}

// AggregateHealth Describes an aggregate hardware health report and its probe results and alerts
type AggregateHealth struct {
	// Describes how the health report was generated
	Source string `json:"source"`
	// Date/time when health report was generated
	ObservedAt NullableTime `json:"observedAt"`
	// Results from successful health probes for the resource
	Successes []HealthProbeSuccess `json:"successes"`
	// Results from failed health probes for the resource
	Alerts []HealthProbeAlert `json:"alerts"`
}

type _AggregateHealth AggregateHealth

// NewAggregateHealth instantiates a new AggregateHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregateHealth(source string, observedAt NullableTime, successes []HealthProbeSuccess, alerts []HealthProbeAlert) *AggregateHealth {
	this := AggregateHealth{}
	this.Source = source
	this.ObservedAt = observedAt
	this.Successes = successes
	this.Alerts = alerts
	return &this
}

// NewAggregateHealthWithDefaults instantiates a new AggregateHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregateHealthWithDefaults() *AggregateHealth {
	this := AggregateHealth{}
	return &this
}

// GetSource returns the Source field value
func (o *AggregateHealth) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *AggregateHealth) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *AggregateHealth) SetSource(v string) {
	o.Source = v
}

// GetObservedAt returns the ObservedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *AggregateHealth) GetObservedAt() time.Time {
	if o == nil || o.ObservedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ObservedAt.Get()
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AggregateHealth) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ObservedAt.Get(), o.ObservedAt.IsSet()
}

// SetObservedAt sets field value
func (o *AggregateHealth) SetObservedAt(v time.Time) {
	o.ObservedAt.Set(&v)
}

// GetSuccesses returns the Successes field value
func (o *AggregateHealth) GetSuccesses() []HealthProbeSuccess {
	if o == nil {
		var ret []HealthProbeSuccess
		return ret
	}

	return o.Successes
}

// GetSuccessesOk returns a tuple with the Successes field value
// and a boolean to check if the value has been set.
func (o *AggregateHealth) GetSuccessesOk() ([]HealthProbeSuccess, bool) {
	if o == nil {
		return nil, false
	}
	return o.Successes, true
}

// SetSuccesses sets field value
func (o *AggregateHealth) SetSuccesses(v []HealthProbeSuccess) {
	o.Successes = v
}

// GetAlerts returns the Alerts field value
func (o *AggregateHealth) GetAlerts() []HealthProbeAlert {
	if o == nil {
		var ret []HealthProbeAlert
		return ret
	}

	return o.Alerts
}

// GetAlertsOk returns a tuple with the Alerts field value
// and a boolean to check if the value has been set.
func (o *AggregateHealth) GetAlertsOk() ([]HealthProbeAlert, bool) {
	if o == nil {
		return nil, false
	}
	return o.Alerts, true
}

// SetAlerts sets field value
func (o *AggregateHealth) SetAlerts(v []HealthProbeAlert) {
	o.Alerts = v
}

func (o AggregateHealth) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregateHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["observedAt"] = o.ObservedAt.Get()
	toSerialize["successes"] = o.Successes
	toSerialize["alerts"] = o.Alerts
	return toSerialize, nil
}

func (o *AggregateHealth) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"observedAt",
		"successes",
		"alerts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggregateHealth := _AggregateHealth{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varAggregateHealth)

	if err != nil {
		return err
	}

	*o = AggregateHealth(varAggregateHealth)

	return err
}

type NullableAggregateHealth struct {
	value *AggregateHealth
	isSet bool
}

func (v NullableAggregateHealth) Get() *AggregateHealth {
	return v.value
}

func (v *NullableAggregateHealth) Set(val *AggregateHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregateHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregateHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregateHealth(val *AggregateHealth) *NullableAggregateHealth {
	return &NullableAggregateHealth{value: val, isSet: true}
}

func (v NullableAggregateHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregateHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
