// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DpuExtensionServiceDpfHelmChartSecurity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuExtensionServiceDpfHelmChartSecurity{}

// DpuExtensionServiceDpfHelmChartSecurity Security settings projected onto the DPF DPUService.
type DpuExtensionServiceDpfHelmChartSecurity struct {
	// DPF privileged-workload setting; false is valid.
	Privileged bool `json:"privileged"`
	// Presence-gated opt-in to SPIFFE workload identity. Supply an empty object to enable it.
	Spiffe map[string]interface{} `json:"spiffe,omitempty"`
}

type _DpuExtensionServiceDpfHelmChartSecurity DpuExtensionServiceDpfHelmChartSecurity

// NewDpuExtensionServiceDpfHelmChartSecurity instantiates a new DpuExtensionServiceDpfHelmChartSecurity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuExtensionServiceDpfHelmChartSecurity(privileged bool) *DpuExtensionServiceDpfHelmChartSecurity {
	this := DpuExtensionServiceDpfHelmChartSecurity{}
	this.Privileged = privileged
	return &this
}

// NewDpuExtensionServiceDpfHelmChartSecurityWithDefaults instantiates a new DpuExtensionServiceDpfHelmChartSecurity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuExtensionServiceDpfHelmChartSecurityWithDefaults() *DpuExtensionServiceDpfHelmChartSecurity {
	this := DpuExtensionServiceDpfHelmChartSecurity{}
	return &this
}

// GetPrivileged returns the Privileged field value
func (o *DpuExtensionServiceDpfHelmChartSecurity) GetPrivileged() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Privileged
}

// GetPrivilegedOk returns a tuple with the Privileged field value
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceDpfHelmChartSecurity) GetPrivilegedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Privileged, true
}

// SetPrivileged sets field value
func (o *DpuExtensionServiceDpfHelmChartSecurity) SetPrivileged(v bool) {
	o.Privileged = v
}

// GetSpiffe returns the Spiffe field value if set, zero value otherwise.
func (o *DpuExtensionServiceDpfHelmChartSecurity) GetSpiffe() map[string]interface{} {
	if o == nil || IsNil(o.Spiffe) {
		var ret map[string]interface{}
		return ret
	}
	return o.Spiffe
}

// GetSpiffeOk returns a tuple with the Spiffe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceDpfHelmChartSecurity) GetSpiffeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Spiffe) {
		return map[string]interface{}{}, false
	}
	return o.Spiffe, true
}

// HasSpiffe returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartSecurity) HasSpiffe() bool {
	if o != nil && !IsNil(o.Spiffe) {
		return true
	}

	return false
}

// SetSpiffe gets a reference to the given map[string]interface{} and assigns it to the Spiffe field.
func (o *DpuExtensionServiceDpfHelmChartSecurity) SetSpiffe(v map[string]interface{}) {
	o.Spiffe = v
}

func (o DpuExtensionServiceDpfHelmChartSecurity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuExtensionServiceDpfHelmChartSecurity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["privileged"] = o.Privileged
	if !IsNil(o.Spiffe) {
		toSerialize["spiffe"] = o.Spiffe
	}
	return toSerialize, nil
}

func (o *DpuExtensionServiceDpfHelmChartSecurity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"privileged",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDpuExtensionServiceDpfHelmChartSecurity := _DpuExtensionServiceDpfHelmChartSecurity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varDpuExtensionServiceDpfHelmChartSecurity)

	if err != nil {
		return err
	}

	*o = DpuExtensionServiceDpfHelmChartSecurity(varDpuExtensionServiceDpfHelmChartSecurity)

	return err
}

type NullableDpuExtensionServiceDpfHelmChartSecurity struct {
	value *DpuExtensionServiceDpfHelmChartSecurity
	isSet bool
}

func (v NullableDpuExtensionServiceDpfHelmChartSecurity) Get() *DpuExtensionServiceDpfHelmChartSecurity {
	return v.value
}

func (v *NullableDpuExtensionServiceDpfHelmChartSecurity) Set(val *DpuExtensionServiceDpfHelmChartSecurity) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceDpfHelmChartSecurity) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceDpfHelmChartSecurity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceDpfHelmChartSecurity(val *DpuExtensionServiceDpfHelmChartSecurity) *NullableDpuExtensionServiceDpfHelmChartSecurity {
	return &NullableDpuExtensionServiceDpfHelmChartSecurity{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceDpfHelmChartSecurity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceDpfHelmChartSecurity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
