// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NVLinkDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NVLinkDomain{}

// NVLinkDomain NVLink Domain inventory and its components.
type NVLinkDomain struct {
	// Case-sensitive Domain ID, equal to its Rack external ID.
	Id string `json:"id"`
	// Domain name, equal to its Rack name.
	Name string `json:"name"`
	// Rack profile ID without the qualified vendor and optional _NO_POWERSHELF suffix. Null when unavailable or unrecognized.
	Topology NullableString `json:"topology"`
	// Operability phase aggregated from the Rack components, not the Core lifecycle state.
	OperationStatus string `json:"operationStatus"`
	// Components belonging to this Domain. Null when includeComponents is false; an empty array when requested but none are known.
	Components []RackComponent `json:"components"`
}

type _NVLinkDomain NVLinkDomain

// NewNVLinkDomain instantiates a new NVLinkDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNVLinkDomain(id string, name string, topology NullableString, operationStatus string, components []RackComponent) *NVLinkDomain {
	this := NVLinkDomain{}
	this.Id = id
	this.Name = name
	this.Topology = topology
	this.OperationStatus = operationStatus
	this.Components = components
	return &this
}

// NewNVLinkDomainWithDefaults instantiates a new NVLinkDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNVLinkDomainWithDefaults() *NVLinkDomain {
	this := NVLinkDomain{}
	return &this
}

// GetId returns the Id field value
func (o *NVLinkDomain) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NVLinkDomain) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NVLinkDomain) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *NVLinkDomain) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NVLinkDomain) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NVLinkDomain) SetName(v string) {
	o.Name = v
}

// GetTopology returns the Topology field value
// If the value is explicit nil, the zero value for string will be returned
func (o *NVLinkDomain) GetTopology() string {
	if o == nil || o.Topology.Get() == nil {
		var ret string
		return ret
	}

	return *o.Topology.Get()
}

// GetTopologyOk returns a tuple with the Topology field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NVLinkDomain) GetTopologyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Topology.Get(), o.Topology.IsSet()
}

// SetTopology sets field value
func (o *NVLinkDomain) SetTopology(v string) {
	o.Topology.Set(&v)
}

// GetOperationStatus returns the OperationStatus field value
func (o *NVLinkDomain) GetOperationStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationStatus
}

// GetOperationStatusOk returns a tuple with the OperationStatus field value
// and a boolean to check if the value has been set.
func (o *NVLinkDomain) GetOperationStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationStatus, true
}

// SetOperationStatus sets field value
func (o *NVLinkDomain) SetOperationStatus(v string) {
	o.OperationStatus = v
}

// GetComponents returns the Components field value
// If the value is explicit nil, the zero value for []RackComponent will be returned
func (o *NVLinkDomain) GetComponents() []RackComponent {
	if o == nil {
		var ret []RackComponent
		return ret
	}

	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value
// and a boolean to check if the value has been set.
func (o *NVLinkDomain) GetComponentsOk() ([]RackComponent, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// SetComponents sets field value
func (o *NVLinkDomain) SetComponents(v []RackComponent) {
	o.Components = v
}

func (o NVLinkDomain) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NVLinkDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["topology"] = o.Topology.Get()
	toSerialize["operationStatus"] = o.OperationStatus
	if o.Components != nil {
		toSerialize["components"] = o.Components
	}
	return toSerialize, nil
}

func (o *NVLinkDomain) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"topology",
		"operationStatus",
		"components",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNVLinkDomain := _NVLinkDomain{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varNVLinkDomain)

	if err != nil {
		return err
	}

	*o = NVLinkDomain(varNVLinkDomain)

	return err
}

type NullableNVLinkDomain struct {
	value *NVLinkDomain
	isSet bool
}

func (v NullableNVLinkDomain) Get() *NVLinkDomain {
	return v.value
}

func (v *NullableNVLinkDomain) Set(val *NVLinkDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableNVLinkDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableNVLinkDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNVLinkDomain(val *NVLinkDomain) *NullableNVLinkDomain {
	return &NullableNVLinkDomain{value: val, isSet: true}
}

func (v NullableNVLinkDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNVLinkDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
