// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VpcPrefixExplicitCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcPrefixExplicitCreateRequest{}

// VpcPrefixExplicitCreateRequest struct for VpcPrefixExplicitCreateRequest
type VpcPrefixExplicitCreateRequest struct {
	Name      string `json:"name"`
	VpcId     string `json:"vpcId"`
	IpBlockId string `json:"ipBlockId"`
	Prefix    string `json:"prefix"`
}

type _VpcPrefixExplicitCreateRequest VpcPrefixExplicitCreateRequest

// NewVpcPrefixExplicitCreateRequest instantiates a new VpcPrefixExplicitCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcPrefixExplicitCreateRequest(name string, vpcId string, ipBlockId string, prefix string) *VpcPrefixExplicitCreateRequest {
	this := VpcPrefixExplicitCreateRequest{}
	this.Name = name
	this.VpcId = vpcId
	this.IpBlockId = ipBlockId
	this.Prefix = prefix
	return &this
}

// NewVpcPrefixExplicitCreateRequestWithDefaults instantiates a new VpcPrefixExplicitCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcPrefixExplicitCreateRequestWithDefaults() *VpcPrefixExplicitCreateRequest {
	this := VpcPrefixExplicitCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *VpcPrefixExplicitCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixExplicitCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VpcPrefixExplicitCreateRequest) SetName(v string) {
	o.Name = v
}

// GetVpcId returns the VpcId field value
func (o *VpcPrefixExplicitCreateRequest) GetVpcId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixExplicitCreateRequest) GetVpcIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpcId, true
}

// SetVpcId sets field value
func (o *VpcPrefixExplicitCreateRequest) SetVpcId(v string) {
	o.VpcId = v
}

// GetIpBlockId returns the IpBlockId field value
func (o *VpcPrefixExplicitCreateRequest) GetIpBlockId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpBlockId
}

// GetIpBlockIdOk returns a tuple with the IpBlockId field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixExplicitCreateRequest) GetIpBlockIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpBlockId, true
}

// SetIpBlockId sets field value
func (o *VpcPrefixExplicitCreateRequest) SetIpBlockId(v string) {
	o.IpBlockId = v
}

// GetPrefix returns the Prefix field value
func (o *VpcPrefixExplicitCreateRequest) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixExplicitCreateRequest) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *VpcPrefixExplicitCreateRequest) SetPrefix(v string) {
	o.Prefix = v
}

func (o VpcPrefixExplicitCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcPrefixExplicitCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["vpcId"] = o.VpcId
	toSerialize["ipBlockId"] = o.IpBlockId
	toSerialize["prefix"] = o.Prefix
	return toSerialize, nil
}

func (o *VpcPrefixExplicitCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"vpcId",
		"ipBlockId",
		"prefix",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcPrefixExplicitCreateRequest := _VpcPrefixExplicitCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varVpcPrefixExplicitCreateRequest)

	if err != nil {
		return err
	}

	*o = VpcPrefixExplicitCreateRequest(varVpcPrefixExplicitCreateRequest)

	return err
}

type NullableVpcPrefixExplicitCreateRequest struct {
	value *VpcPrefixExplicitCreateRequest
	isSet bool
}

func (v NullableVpcPrefixExplicitCreateRequest) Get() *VpcPrefixExplicitCreateRequest {
	return v.value
}

func (v *NullableVpcPrefixExplicitCreateRequest) Set(val *VpcPrefixExplicitCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcPrefixExplicitCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcPrefixExplicitCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcPrefixExplicitCreateRequest(val *VpcPrefixExplicitCreateRequest) *NullableVpcPrefixExplicitCreateRequest {
	return &NullableVpcPrefixExplicitCreateRequest{value: val, isSet: true}
}

func (v NullableVpcPrefixExplicitCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcPrefixExplicitCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
