// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedSwitchList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedSwitchList{}

// ExpectedSwitchList Complete replacement set of Expected Switches for one Site. Every entry must use the top-level `siteId`; the array may be empty to clear the set.
type ExpectedSwitchList struct {
	// ID of the Site whose Expected Switches should be replaced
	SiteId string `json:"siteId"`
	// Full desired Expected Switch set; BMC MAC addresses, serial numbers, and NVOS MAC addresses must be unique
	ExpectedSwitches []ExpectedSwitchCreateRequest `json:"expectedSwitches"`
}

type _ExpectedSwitchList ExpectedSwitchList

// NewExpectedSwitchList instantiates a new ExpectedSwitchList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedSwitchList(siteId string, expectedSwitches []ExpectedSwitchCreateRequest) *ExpectedSwitchList {
	this := ExpectedSwitchList{}
	this.SiteId = siteId
	this.ExpectedSwitches = expectedSwitches
	return &this
}

// NewExpectedSwitchListWithDefaults instantiates a new ExpectedSwitchList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedSwitchListWithDefaults() *ExpectedSwitchList {
	this := ExpectedSwitchList{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedSwitchList) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedSwitchList) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedSwitchList) SetSiteId(v string) {
	o.SiteId = v
}

// GetExpectedSwitches returns the ExpectedSwitches field value
func (o *ExpectedSwitchList) GetExpectedSwitches() []ExpectedSwitchCreateRequest {
	if o == nil {
		var ret []ExpectedSwitchCreateRequest
		return ret
	}

	return o.ExpectedSwitches
}

// GetExpectedSwitchesOk returns a tuple with the ExpectedSwitches field value
// and a boolean to check if the value has been set.
func (o *ExpectedSwitchList) GetExpectedSwitchesOk() ([]ExpectedSwitchCreateRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedSwitches, true
}

// SetExpectedSwitches sets field value
func (o *ExpectedSwitchList) SetExpectedSwitches(v []ExpectedSwitchCreateRequest) {
	o.ExpectedSwitches = v
}

func (o ExpectedSwitchList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedSwitchList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["expectedSwitches"] = o.ExpectedSwitches
	return toSerialize, nil
}

func (o *ExpectedSwitchList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"expectedSwitches",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedSwitchList := _ExpectedSwitchList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExpectedSwitchList)

	if err != nil {
		return err
	}

	*o = ExpectedSwitchList(varExpectedSwitchList)

	return err
}

type NullableExpectedSwitchList struct {
	value *ExpectedSwitchList
	isSet bool
}

func (v NullableExpectedSwitchList) Get() *ExpectedSwitchList {
	return v.value
}

func (v *NullableExpectedSwitchList) Set(val *ExpectedSwitchList) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedSwitchList) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedSwitchList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedSwitchList(val *ExpectedSwitchList) *NullableExpectedSwitchList {
	return &NullableExpectedSwitchList{value: val, isSet: true}
}

func (v NullableExpectedSwitchList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedSwitchList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
