// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VpcPrefixAutomaticCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcPrefixAutomaticCreateRequest{}

// VpcPrefixAutomaticCreateRequest struct for VpcPrefixAutomaticCreateRequest
type VpcPrefixAutomaticCreateRequest struct {
	Name         string `json:"name"`
	VpcId        string `json:"vpcId"`
	IpBlockId    string `json:"ipBlockId"`
	PrefixLength int32  `json:"prefixLength"`
}

type _VpcPrefixAutomaticCreateRequest VpcPrefixAutomaticCreateRequest

// NewVpcPrefixAutomaticCreateRequest instantiates a new VpcPrefixAutomaticCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcPrefixAutomaticCreateRequest(name string, vpcId string, ipBlockId string, prefixLength int32) *VpcPrefixAutomaticCreateRequest {
	this := VpcPrefixAutomaticCreateRequest{}
	this.Name = name
	this.VpcId = vpcId
	this.IpBlockId = ipBlockId
	this.PrefixLength = prefixLength
	return &this
}

// NewVpcPrefixAutomaticCreateRequestWithDefaults instantiates a new VpcPrefixAutomaticCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcPrefixAutomaticCreateRequestWithDefaults() *VpcPrefixAutomaticCreateRequest {
	this := VpcPrefixAutomaticCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *VpcPrefixAutomaticCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixAutomaticCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VpcPrefixAutomaticCreateRequest) SetName(v string) {
	o.Name = v
}

// GetVpcId returns the VpcId field value
func (o *VpcPrefixAutomaticCreateRequest) GetVpcId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixAutomaticCreateRequest) GetVpcIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpcId, true
}

// SetVpcId sets field value
func (o *VpcPrefixAutomaticCreateRequest) SetVpcId(v string) {
	o.VpcId = v
}

// GetIpBlockId returns the IpBlockId field value
func (o *VpcPrefixAutomaticCreateRequest) GetIpBlockId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpBlockId
}

// GetIpBlockIdOk returns a tuple with the IpBlockId field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixAutomaticCreateRequest) GetIpBlockIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpBlockId, true
}

// SetIpBlockId sets field value
func (o *VpcPrefixAutomaticCreateRequest) SetIpBlockId(v string) {
	o.IpBlockId = v
}

// GetPrefixLength returns the PrefixLength field value
func (o *VpcPrefixAutomaticCreateRequest) GetPrefixLength() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PrefixLength
}

// GetPrefixLengthOk returns a tuple with the PrefixLength field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixAutomaticCreateRequest) GetPrefixLengthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrefixLength, true
}

// SetPrefixLength sets field value
func (o *VpcPrefixAutomaticCreateRequest) SetPrefixLength(v int32) {
	o.PrefixLength = v
}

func (o VpcPrefixAutomaticCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcPrefixAutomaticCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["vpcId"] = o.VpcId
	toSerialize["ipBlockId"] = o.IpBlockId
	toSerialize["prefixLength"] = o.PrefixLength
	return toSerialize, nil
}

func (o *VpcPrefixAutomaticCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"vpcId",
		"ipBlockId",
		"prefixLength",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcPrefixAutomaticCreateRequest := _VpcPrefixAutomaticCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varVpcPrefixAutomaticCreateRequest)

	if err != nil {
		return err
	}

	*o = VpcPrefixAutomaticCreateRequest(varVpcPrefixAutomaticCreateRequest)

	return err
}

type NullableVpcPrefixAutomaticCreateRequest struct {
	value *VpcPrefixAutomaticCreateRequest
	isSet bool
}

func (v NullableVpcPrefixAutomaticCreateRequest) Get() *VpcPrefixAutomaticCreateRequest {
	return v.value
}

func (v *NullableVpcPrefixAutomaticCreateRequest) Set(val *VpcPrefixAutomaticCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcPrefixAutomaticCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcPrefixAutomaticCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcPrefixAutomaticCreateRequest(val *VpcPrefixAutomaticCreateRequest) *NullableVpcPrefixAutomaticCreateRequest {
	return &NullableVpcPrefixAutomaticCreateRequest{value: val, isSet: true}
}

func (v NullableVpcPrefixAutomaticCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcPrefixAutomaticCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
