// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MachineHealthIssue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineHealthIssue{}

// MachineHealthIssue Tenant-reported Machine issue, attached to a Machine online repair request or an Instance delete request. Categories match the Core `IssueCategory` values.
type MachineHealthIssue struct {
	// High-level category for the tenant-reported issue.
	Category string `json:"category"`
	// Brief description of the issue for operators.
	Summary string `json:"summary"`
	// Diagnostic information, logs, ticket numbers, etc. Required when entering Machine online repair.
	Details NullableString `json:"details,omitempty"`
}

type _MachineHealthIssue MachineHealthIssue

// NewMachineHealthIssue instantiates a new MachineHealthIssue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineHealthIssue(category string, summary string) *MachineHealthIssue {
	this := MachineHealthIssue{}
	this.Category = category
	this.Summary = summary
	return &this
}

// NewMachineHealthIssueWithDefaults instantiates a new MachineHealthIssue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineHealthIssueWithDefaults() *MachineHealthIssue {
	this := MachineHealthIssue{}
	return &this
}

// GetCategory returns the Category field value
func (o *MachineHealthIssue) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *MachineHealthIssue) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *MachineHealthIssue) SetCategory(v string) {
	o.Category = v
}

// GetSummary returns the Summary field value
func (o *MachineHealthIssue) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *MachineHealthIssue) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *MachineHealthIssue) SetSummary(v string) {
	o.Summary = v
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineHealthIssue) GetDetails() string {
	if o == nil || IsNil(o.Details.Get()) {
		var ret string
		return ret
	}
	return *o.Details.Get()
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineHealthIssue) GetDetailsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Details.Get(), o.Details.IsSet()
}

// HasDetails returns a boolean if a field has been set.
func (o *MachineHealthIssue) HasDetails() bool {
	if o != nil && o.Details.IsSet() {
		return true
	}

	return false
}

// SetDetails gets a reference to the given NullableString and assigns it to the Details field.
func (o *MachineHealthIssue) SetDetails(v string) {
	o.Details.Set(&v)
}

// SetDetailsNil sets the value for Details to be an explicit nil
func (o *MachineHealthIssue) SetDetailsNil() {
	o.Details.Set(nil)
}

// UnsetDetails ensures that no value is present for Details, not even an explicit nil
func (o *MachineHealthIssue) UnsetDetails() {
	o.Details.Unset()
}

func (o MachineHealthIssue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineHealthIssue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["category"] = o.Category
	toSerialize["summary"] = o.Summary
	if o.Details.IsSet() {
		toSerialize["details"] = o.Details.Get()
	}
	return toSerialize, nil
}

func (o *MachineHealthIssue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"category",
		"summary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMachineHealthIssue := _MachineHealthIssue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varMachineHealthIssue)

	if err != nil {
		return err
	}

	*o = MachineHealthIssue(varMachineHealthIssue)

	return err
}

type NullableMachineHealthIssue struct {
	value *MachineHealthIssue
	isSet bool
}

func (v NullableMachineHealthIssue) Get() *MachineHealthIssue {
	return v.value
}

func (v *NullableMachineHealthIssue) Set(val *MachineHealthIssue) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineHealthIssue) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineHealthIssue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineHealthIssue(val *MachineHealthIssue) *NullableMachineHealthIssue {
	return &NullableMachineHealthIssue{value: val, isSet: true}
}

func (v NullableMachineHealthIssue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineHealthIssue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
