// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedRackGroupRack type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedRackGroupRack{}

// ExpectedRackGroupRack One expected rack and its devices. Declaration may precede rack ingestion. Members omitted or null are treated as []; responses always return arrays.
type ExpectedRackGroupRack struct {
	// Non-blank, case-sensitive external rack identifier, unique within the group.
	RackId string `json:"rackId" validate:"regexp=\\S"`
	// Ordered devices in this rack. Device identities are unique across all racks in the group.
	Members []ExpectedRackGroupMember `json:"members,omitempty"`
}

type _ExpectedRackGroupRack ExpectedRackGroupRack

// NewExpectedRackGroupRack instantiates a new ExpectedRackGroupRack object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedRackGroupRack(rackId string) *ExpectedRackGroupRack {
	this := ExpectedRackGroupRack{}
	this.RackId = rackId
	return &this
}

// NewExpectedRackGroupRackWithDefaults instantiates a new ExpectedRackGroupRack object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedRackGroupRackWithDefaults() *ExpectedRackGroupRack {
	this := ExpectedRackGroupRack{}
	return &this
}

// GetRackId returns the RackId field value
func (o *ExpectedRackGroupRack) GetRackId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RackId
}

// GetRackIdOk returns a tuple with the RackId field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupRack) GetRackIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RackId, true
}

// SetRackId sets field value
func (o *ExpectedRackGroupRack) SetRackId(v string) {
	o.RackId = v
}

// GetMembers returns the Members field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupRack) GetMembers() []ExpectedRackGroupMember {
	if o == nil {
		var ret []ExpectedRackGroupMember
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupRack) GetMembersOk() ([]ExpectedRackGroupMember, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *ExpectedRackGroupRack) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []ExpectedRackGroupMember and assigns it to the Members field.
func (o *ExpectedRackGroupRack) SetMembers(v []ExpectedRackGroupMember) {
	o.Members = v
}

func (o ExpectedRackGroupRack) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedRackGroupRack) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rackId"] = o.RackId
	if o.Members != nil {
		toSerialize["members"] = o.Members
	}
	return toSerialize, nil
}

func (o *ExpectedRackGroupRack) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rackId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedRackGroupRack := _ExpectedRackGroupRack{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExpectedRackGroupRack)

	if err != nil {
		return err
	}

	*o = ExpectedRackGroupRack(varExpectedRackGroupRack)

	return err
}

type NullableExpectedRackGroupRack struct {
	value *ExpectedRackGroupRack
	isSet bool
}

func (v NullableExpectedRackGroupRack) Get() *ExpectedRackGroupRack {
	return v.value
}

func (v *NullableExpectedRackGroupRack) Set(val *ExpectedRackGroupRack) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedRackGroupRack) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedRackGroupRack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedRackGroupRack(val *ExpectedRackGroupRack) *NullableExpectedRackGroupRack {
	return &NullableExpectedRackGroupRack{value: val, isSet: true}
}

func (v NullableExpectedRackGroupRack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedRackGroupRack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
