// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the HealthProbeAlert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthProbeAlert{}

// HealthProbeAlert Describes a failed health probe result
type HealthProbeAlert struct {
	// Health probe identifier
	Id string `json:"id"`
	// Specific component targeted by health probe
	Target NullableString `json:"target"`
	// Date/time since the alert has been in effect
	InAlertSince NullableTime `json:"inAlertSince"`
	// Details of the failed health probe result
	Message string `json:"message"`
	// Information provided by Tenant, if any
	TenantMessage NullableString `json:"tenantMessage"`
	// Classifications for this alert, category or impact
	Classifications []string `json:"classifications"`
}

type _HealthProbeAlert HealthProbeAlert

// NewHealthProbeAlert instantiates a new HealthProbeAlert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthProbeAlert(id string, target NullableString, inAlertSince NullableTime, message string, tenantMessage NullableString, classifications []string) *HealthProbeAlert {
	this := HealthProbeAlert{}
	this.Id = id
	this.Target = target
	this.InAlertSince = inAlertSince
	this.Message = message
	this.TenantMessage = tenantMessage
	this.Classifications = classifications
	return &this
}

// NewHealthProbeAlertWithDefaults instantiates a new HealthProbeAlert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthProbeAlertWithDefaults() *HealthProbeAlert {
	this := HealthProbeAlert{}
	return &this
}

// GetId returns the Id field value
func (o *HealthProbeAlert) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HealthProbeAlert) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HealthProbeAlert) SetId(v string) {
	o.Id = v
}

// GetTarget returns the Target field value
// If the value is explicit nil, the zero value for string will be returned
func (o *HealthProbeAlert) GetTarget() string {
	if o == nil || o.Target.Get() == nil {
		var ret string
		return ret
	}

	return *o.Target.Get()
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthProbeAlert) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Target.Get(), o.Target.IsSet()
}

// SetTarget sets field value
func (o *HealthProbeAlert) SetTarget(v string) {
	o.Target.Set(&v)
}

// GetInAlertSince returns the InAlertSince field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *HealthProbeAlert) GetInAlertSince() time.Time {
	if o == nil || o.InAlertSince.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.InAlertSince.Get()
}

// GetInAlertSinceOk returns a tuple with the InAlertSince field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthProbeAlert) GetInAlertSinceOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.InAlertSince.Get(), o.InAlertSince.IsSet()
}

// SetInAlertSince sets field value
func (o *HealthProbeAlert) SetInAlertSince(v time.Time) {
	o.InAlertSince.Set(&v)
}

// GetMessage returns the Message field value
func (o *HealthProbeAlert) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *HealthProbeAlert) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *HealthProbeAlert) SetMessage(v string) {
	o.Message = v
}

// GetTenantMessage returns the TenantMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *HealthProbeAlert) GetTenantMessage() string {
	if o == nil || o.TenantMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.TenantMessage.Get()
}

// GetTenantMessageOk returns a tuple with the TenantMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthProbeAlert) GetTenantMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantMessage.Get(), o.TenantMessage.IsSet()
}

// SetTenantMessage sets field value
func (o *HealthProbeAlert) SetTenantMessage(v string) {
	o.TenantMessage.Set(&v)
}

// GetClassifications returns the Classifications field value
func (o *HealthProbeAlert) GetClassifications() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Classifications
}

// GetClassificationsOk returns a tuple with the Classifications field value
// and a boolean to check if the value has been set.
func (o *HealthProbeAlert) GetClassificationsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Classifications, true
}

// SetClassifications sets field value
func (o *HealthProbeAlert) SetClassifications(v []string) {
	o.Classifications = v
}

func (o HealthProbeAlert) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthProbeAlert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["target"] = o.Target.Get()
	toSerialize["inAlertSince"] = o.InAlertSince.Get()
	toSerialize["message"] = o.Message
	toSerialize["tenantMessage"] = o.TenantMessage.Get()
	toSerialize["classifications"] = o.Classifications
	return toSerialize, nil
}

func (o *HealthProbeAlert) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"target",
		"inAlertSince",
		"message",
		"tenantMessage",
		"classifications",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthProbeAlert := _HealthProbeAlert{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varHealthProbeAlert)

	if err != nil {
		return err
	}

	*o = HealthProbeAlert(varHealthProbeAlert)

	return err
}

type NullableHealthProbeAlert struct {
	value *HealthProbeAlert
	isSet bool
}

func (v NullableHealthProbeAlert) Get() *HealthProbeAlert {
	return v.value
}

func (v *NullableHealthProbeAlert) Set(val *HealthProbeAlert) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthProbeAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthProbeAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthProbeAlert(val *HealthProbeAlert) *NullableHealthProbeAlert {
	return &NullableHealthProbeAlert{value: val, isSet: true}
}

func (v NullableHealthProbeAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthProbeAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
