// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SubnetAttachVpcRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetAttachVpcRequest{}

// SubnetAttachVpcRequest Request data for attaching a Subnet to a VPC. The operation cannot detach a Subnet from all VPCs.
type SubnetAttachVpcRequest struct {
	// ID of the target Ethernet virtualizer VPC at the same Site and owned by the same Tenant
	VpcId string `json:"vpcId"`
	// Whether an existing attachment to a different VPC may be replaced
	AllowReplace *bool `json:"allowReplace,omitempty"`
}

type _SubnetAttachVpcRequest SubnetAttachVpcRequest

// NewSubnetAttachVpcRequest instantiates a new SubnetAttachVpcRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetAttachVpcRequest(vpcId string) *SubnetAttachVpcRequest {
	this := SubnetAttachVpcRequest{}
	this.VpcId = vpcId
	var allowReplace bool = false
	this.AllowReplace = &allowReplace
	return &this
}

// NewSubnetAttachVpcRequestWithDefaults instantiates a new SubnetAttachVpcRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetAttachVpcRequestWithDefaults() *SubnetAttachVpcRequest {
	this := SubnetAttachVpcRequest{}
	var allowReplace bool = false
	this.AllowReplace = &allowReplace
	return &this
}

// GetVpcId returns the VpcId field value
func (o *SubnetAttachVpcRequest) GetVpcId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value
// and a boolean to check if the value has been set.
func (o *SubnetAttachVpcRequest) GetVpcIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpcId, true
}

// SetVpcId sets field value
func (o *SubnetAttachVpcRequest) SetVpcId(v string) {
	o.VpcId = v
}

// GetAllowReplace returns the AllowReplace field value if set, zero value otherwise.
func (o *SubnetAttachVpcRequest) GetAllowReplace() bool {
	if o == nil || IsNil(o.AllowReplace) {
		var ret bool
		return ret
	}
	return *o.AllowReplace
}

// GetAllowReplaceOk returns a tuple with the AllowReplace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetAttachVpcRequest) GetAllowReplaceOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowReplace) {
		return nil, false
	}
	return o.AllowReplace, true
}

// HasAllowReplace returns a boolean if a field has been set.
func (o *SubnetAttachVpcRequest) HasAllowReplace() bool {
	if o != nil && !IsNil(o.AllowReplace) {
		return true
	}

	return false
}

// SetAllowReplace gets a reference to the given bool and assigns it to the AllowReplace field.
func (o *SubnetAttachVpcRequest) SetAllowReplace(v bool) {
	o.AllowReplace = &v
}

func (o SubnetAttachVpcRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetAttachVpcRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vpcId"] = o.VpcId
	if !IsNil(o.AllowReplace) {
		toSerialize["allowReplace"] = o.AllowReplace
	}
	return toSerialize, nil
}

func (o *SubnetAttachVpcRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vpcId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubnetAttachVpcRequest := _SubnetAttachVpcRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSubnetAttachVpcRequest)

	if err != nil {
		return err
	}

	*o = SubnetAttachVpcRequest(varSubnetAttachVpcRequest)

	return err
}

type NullableSubnetAttachVpcRequest struct {
	value *SubnetAttachVpcRequest
	isSet bool
}

func (v NullableSubnetAttachVpcRequest) Get() *SubnetAttachVpcRequest {
	return v.value
}

func (v *NullableSubnetAttachVpcRequest) Set(val *SubnetAttachVpcRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetAttachVpcRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetAttachVpcRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetAttachVpcRequest(val *SubnetAttachVpcRequest) *NullableSubnetAttachVpcRequest {
	return &NullableSubnetAttachVpcRequest{value: val, isSet: true}
}

func (v NullableSubnetAttachVpcRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetAttachVpcRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
