// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// VpcPrefixCreateRequest - Specify exactly one non-null allocation selector. Use `prefixLength` for automatic allocation or `prefix` to reserve an exact CIDR. The allocated prefix is immutable.
type VpcPrefixCreateRequest struct {
	VpcPrefixAutomaticCreateRequest *VpcPrefixAutomaticCreateRequest
	VpcPrefixExplicitCreateRequest  *VpcPrefixExplicitCreateRequest
}

// VpcPrefixAutomaticCreateRequestAsVpcPrefixCreateRequest is a convenience function that returns VpcPrefixAutomaticCreateRequest wrapped in VpcPrefixCreateRequest
func VpcPrefixAutomaticCreateRequestAsVpcPrefixCreateRequest(v *VpcPrefixAutomaticCreateRequest) VpcPrefixCreateRequest {
	return VpcPrefixCreateRequest{
		VpcPrefixAutomaticCreateRequest: v,
	}
}

// VpcPrefixExplicitCreateRequestAsVpcPrefixCreateRequest is a convenience function that returns VpcPrefixExplicitCreateRequest wrapped in VpcPrefixCreateRequest
func VpcPrefixExplicitCreateRequestAsVpcPrefixCreateRequest(v *VpcPrefixExplicitCreateRequest) VpcPrefixCreateRequest {
	return VpcPrefixCreateRequest{
		VpcPrefixExplicitCreateRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *VpcPrefixCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into VpcPrefixAutomaticCreateRequest
	err = newStrictDecoder(data).Decode(&dst.VpcPrefixAutomaticCreateRequest)
	if err == nil {
		jsonVpcPrefixAutomaticCreateRequest, _ := json.Marshal(dst.VpcPrefixAutomaticCreateRequest)
		if string(jsonVpcPrefixAutomaticCreateRequest) == "{}" { // empty struct
			dst.VpcPrefixAutomaticCreateRequest = nil
		} else {
			if err = validator.Validate(dst.VpcPrefixAutomaticCreateRequest); err != nil {
				dst.VpcPrefixAutomaticCreateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.VpcPrefixAutomaticCreateRequest = nil
	}

	// try to unmarshal data into VpcPrefixExplicitCreateRequest
	err = newStrictDecoder(data).Decode(&dst.VpcPrefixExplicitCreateRequest)
	if err == nil {
		jsonVpcPrefixExplicitCreateRequest, _ := json.Marshal(dst.VpcPrefixExplicitCreateRequest)
		if string(jsonVpcPrefixExplicitCreateRequest) == "{}" { // empty struct
			dst.VpcPrefixExplicitCreateRequest = nil
		} else {
			if err = validator.Validate(dst.VpcPrefixExplicitCreateRequest); err != nil {
				dst.VpcPrefixExplicitCreateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.VpcPrefixExplicitCreateRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.VpcPrefixAutomaticCreateRequest = nil
		dst.VpcPrefixExplicitCreateRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(VpcPrefixCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(VpcPrefixCreateRequest): %v", err)
		}
		return fmt.Errorf("data failed to match schemas in oneOf(VpcPrefixCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VpcPrefixCreateRequest) MarshalJSON() ([]byte, error) {
	if src.VpcPrefixAutomaticCreateRequest != nil {
		return json.Marshal(&src.VpcPrefixAutomaticCreateRequest)
	}

	if src.VpcPrefixExplicitCreateRequest != nil {
		return json.Marshal(&src.VpcPrefixExplicitCreateRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VpcPrefixCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.VpcPrefixAutomaticCreateRequest != nil {
		return obj.VpcPrefixAutomaticCreateRequest
	}

	if obj.VpcPrefixExplicitCreateRequest != nil {
		return obj.VpcPrefixExplicitCreateRequest
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj VpcPrefixCreateRequest) GetActualInstanceValue() interface{} {
	if obj.VpcPrefixAutomaticCreateRequest != nil {
		return *obj.VpcPrefixAutomaticCreateRequest
	}

	if obj.VpcPrefixExplicitCreateRequest != nil {
		return *obj.VpcPrefixExplicitCreateRequest
	}

	// all schemas are nil
	return nil
}

type NullableVpcPrefixCreateRequest struct {
	value *VpcPrefixCreateRequest
	isSet bool
}

func (v NullableVpcPrefixCreateRequest) Get() *VpcPrefixCreateRequest {
	return v.value
}

func (v *NullableVpcPrefixCreateRequest) Set(val *VpcPrefixCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcPrefixCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcPrefixCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcPrefixCreateRequest(val *VpcPrefixCreateRequest) *NullableVpcPrefixCreateRequest {
	return &NullableVpcPrefixCreateRequest{value: val, isSet: true}
}

func (v NullableVpcPrefixCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcPrefixCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
