// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HealthProbeSuccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthProbeSuccess{}

// HealthProbeSuccess Describes a successful health probe result
type HealthProbeSuccess struct {
	// Health probe identifier
	Id string `json:"id"`
	// Specific component targeted by health probe
	Target NullableString `json:"target"`
}

type _HealthProbeSuccess HealthProbeSuccess

// NewHealthProbeSuccess instantiates a new HealthProbeSuccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthProbeSuccess(id string, target NullableString) *HealthProbeSuccess {
	this := HealthProbeSuccess{}
	this.Id = id
	this.Target = target
	return &this
}

// NewHealthProbeSuccessWithDefaults instantiates a new HealthProbeSuccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthProbeSuccessWithDefaults() *HealthProbeSuccess {
	this := HealthProbeSuccess{}
	return &this
}

// GetId returns the Id field value
func (o *HealthProbeSuccess) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HealthProbeSuccess) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HealthProbeSuccess) SetId(v string) {
	o.Id = v
}

// GetTarget returns the Target field value
// If the value is explicit nil, the zero value for string will be returned
func (o *HealthProbeSuccess) GetTarget() string {
	if o == nil || o.Target.Get() == nil {
		var ret string
		return ret
	}

	return *o.Target.Get()
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthProbeSuccess) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Target.Get(), o.Target.IsSet()
}

// SetTarget sets field value
func (o *HealthProbeSuccess) SetTarget(v string) {
	o.Target.Set(&v)
}

func (o HealthProbeSuccess) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthProbeSuccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["target"] = o.Target.Get()
	return toSerialize, nil
}

func (o *HealthProbeSuccess) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthProbeSuccess := _HealthProbeSuccess{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varHealthProbeSuccess)

	if err != nil {
		return err
	}

	*o = HealthProbeSuccess(varHealthProbeSuccess)

	return err
}

type NullableHealthProbeSuccess struct {
	value *HealthProbeSuccess
	isSet bool
}

func (v NullableHealthProbeSuccess) Get() *HealthProbeSuccess {
	return v.value
}

func (v *NullableHealthProbeSuccess) Set(val *HealthProbeSuccess) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthProbeSuccess) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthProbeSuccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthProbeSuccess(val *HealthProbeSuccess) *NullableHealthProbeSuccess {
	return &NullableHealthProbeSuccess{value: val, isSet: true}
}

func (v NullableHealthProbeSuccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthProbeSuccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
