// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedMachineList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedMachineList{}

// ExpectedMachineList Complete replacement set of Expected Machines for one Site. Every entry must use the top-level `siteId`; the array may be empty to clear the set.
type ExpectedMachineList struct {
	// ID of the Site whose Expected Machines should be replaced
	SiteId string `json:"siteId"`
	// Full desired Expected Machine set; BMC MAC addresses and chassis serial numbers must be unique
	ExpectedMachines []ExpectedMachineCreateRequest `json:"expectedMachines"`
}

type _ExpectedMachineList ExpectedMachineList

// NewExpectedMachineList instantiates a new ExpectedMachineList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedMachineList(siteId string, expectedMachines []ExpectedMachineCreateRequest) *ExpectedMachineList {
	this := ExpectedMachineList{}
	this.SiteId = siteId
	this.ExpectedMachines = expectedMachines
	return &this
}

// NewExpectedMachineListWithDefaults instantiates a new ExpectedMachineList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedMachineListWithDefaults() *ExpectedMachineList {
	this := ExpectedMachineList{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedMachineList) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedMachineList) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedMachineList) SetSiteId(v string) {
	o.SiteId = v
}

// GetExpectedMachines returns the ExpectedMachines field value
func (o *ExpectedMachineList) GetExpectedMachines() []ExpectedMachineCreateRequest {
	if o == nil {
		var ret []ExpectedMachineCreateRequest
		return ret
	}

	return o.ExpectedMachines
}

// GetExpectedMachinesOk returns a tuple with the ExpectedMachines field value
// and a boolean to check if the value has been set.
func (o *ExpectedMachineList) GetExpectedMachinesOk() ([]ExpectedMachineCreateRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedMachines, true
}

// SetExpectedMachines sets field value
func (o *ExpectedMachineList) SetExpectedMachines(v []ExpectedMachineCreateRequest) {
	o.ExpectedMachines = v
}

func (o ExpectedMachineList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedMachineList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["expectedMachines"] = o.ExpectedMachines
	return toSerialize, nil
}

func (o *ExpectedMachineList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"expectedMachines",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedMachineList := _ExpectedMachineList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExpectedMachineList)

	if err != nil {
		return err
	}

	*o = ExpectedMachineList(varExpectedMachineList)

	return err
}

type NullableExpectedMachineList struct {
	value *ExpectedMachineList
	isSet bool
}

func (v NullableExpectedMachineList) Get() *ExpectedMachineList {
	return v.value
}

func (v *NullableExpectedMachineList) Set(val *ExpectedMachineList) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedMachineList) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedMachineList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedMachineList(val *ExpectedMachineList) *NullableExpectedMachineList {
	return &NullableExpectedMachineList{value: val, isSet: true}
}

func (v NullableExpectedMachineList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedMachineList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
